src/Entity/Prestations.php
<?php

namespace App\Entity;

use App\Repository\PrestationsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PrestationsRepository::class)]
class Prestations
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $long_description = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $created_at = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $updated_at = null;

    #[ORM\OneToOne(mappedBy: 'prestation', cascade: ['persist', 'remove'])]
    private ?Reservation $reservation = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $during_time = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getLongDescription(): ?string
    {
        return $this->long_description;
    }

    public function setLongDescription(?string $long_description): self
    {
        $this->long_description = $long_description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getReservation(): ?Reservation
    {
        return $this->reservation;
    }

    public function setReservation(?Reservation $reservation): self
    {
        // unset the owning side of the relation if necessary
        if ($reservation === null && $this->reservation !== null) {
            $this->reservation->setPrestation(null);
        }

        // set the owning side of the relation if necessary
        if ($reservation !== null && $reservation->getPrestation() !== $this) {
            $reservation->setPrestation($this);
        }

        $this->reservation = $reservation;

        return $this;
    }

    public function getDuringTime(): ?\DateTimeInterface
    {
        return $this->during_time;
    }

    public function setDuringTime(\DateTimeInterface $during_time): self
    {
        $this->during_time = $during_time;

        return $this;
    }
}

src/Controller/PrestationController.php
<?php

namespace App\Controller;

use App\Repository\PrestationsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PrestationController extends AbstractController
{
    public function __construct(private readonly PrestationsRepository $prestationsRepository)
    {
    }
    #[Route('/prestations', name: 'app_prestations')]
    public function index(): Response
    {
        $prestations = $this->prestationsRepository->findAll();
        return $this->render('prestation/index.html.twig', [
            'prestations' => $prestations
        ]);
    }

    #[Route('/prestation/detail/{id}', name: 'app_blog_prestation_detail', requirements: ['id' => '\d+'])]
    public function detail($id): Response
    {
        $prestation = $this->prestationsRepository->findOneBy(['id' => $id]);
        return $this->render('prestation/detail.html.twig', [
            'prestation' => $prestation
        ]);
    }
}

templates/prestation/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ prestation.name }}{% endblock %}

{% block menu %}
    {% include '/includes/menu.html.twig' %}
{% endblock %}
{% block body %}
    <style>
        .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
        .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    </style>

    <div class="example-wrapper">
        <h1>{{ prestation.name }}</h1>
        <div>
            {{ dump(prestation) }}
            <p>{{ prestation.description }}</p>
            <p>{{ prestation.longDescription }}</p>
            <form action="{{ path('app_booking', {id: prestation.id}) }}">
                <button type="submit">Réserver</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/prestation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Prestations{% endblock %}
{% block menu %}
    {% include '/includes/menu.html.twig' %}
{% endblock %}
{% block body %}

    <h1>Mes préstations</h1>
    {% if prestations %}
        {% for prestation in prestations %}
            <div class="app-content-prestation">
                <h2>
                    <a href="{{ path('app_blog_prestation_detail', {id: prestation.id}) }}">
                        {{ prestation.name }}
                    </a>
                </h2>
                <p>{{ prestation.description }}</p>
                <p>{{ prestation.longDescription }}</p>
                <a href="{{ path('app_blog_prestation_detail', {id: prestation.id}) }}">
                    <button class="pure-button app-pure-button-violet">
{#                        Réserver la {{ prestation.name|lower }}#}
                        Réserver la consultation
                    </button>
                </a>
            </div>
        {% endfor %}
    {% endif %}
{% endblock %}